### ISSUE TITLE
Funni crash

### ISSUE THREAD

**Issue by valoeghese** [valoeghese/2fc0f18#20]
Exception in thread "main" tk.valoeghese.sod.exception.SODParseException: Unhandled IOException in parsing file .\saves\save_1\c-21.9.gsod
	at tk.valoeghese.sod.BinaryData.readGzipped(BinaryData.java:130)
	at tk.valoeghese.fc0.world.save.Save.getOrCreateChunk(Save.java:233)
	at tk.valoeghese.fc0.world.GameplayWorld.getOrCreateChunk(GameplayWorld.java:83)
	at tk.valoeghese.fc0.world.GameplayWorld.loadChunk(GameplayWorld.java:138)
	at tk.valoeghese.fc0.client.world.ClientWorld.loadChunk(ClientWorld.java:30)
	at tk.valoeghese.fc0.world.Chunk.getChunk(Chunk.java:556)
	at tk.valoeghese.fc0.client.world.ClientChunk.south(ClientChunk.java:89)
	at tk.valoeghese.fc0.client.render.model.ChunkMesh.buildMesh(ChunkMesh.java:70)
	at tk.valoeghese.fc0.client.world.ClientChunk.rebuildMesh(ClientChunk.java:122)
	at tk.valoeghese.fc0.client.world.ClientChunk.writeTile(ClientChunk.java:52)
	at tk.valoeghese.fc0.world.gen.GenWorld.wgWriteTile(GenWorld.java:21)
	at tk.valoeghese.fc0.world.GameplayWorld$GeneratorWorldAccess.wgWriteTile(GameplayWorld.java:354)
	at tk.valoeghese.fc0.world.gen.generator.ScatteredOreGenerator.generate(ScatteredOreGenerator.java:24)
	at tk.valoeghese.fc0.world.gen.generator.ScatteredOreGenerator.generate(ScatteredOreGenerator.java:8)
	at tk.valoeghese.fc0.world.gen.WorldGen.populateChunk(WorldGen.java:100)
	at tk.valoeghese.fc0.world.GameplayWorld.loadChunk(GameplayWorld.java:160)
	at tk.valoeghese.fc0.client.world.ClientWorld.loadChunk(ClientWorld.java:30)
	at tk.valoeghese.fc0.world.Chunk.getChunk(Chunk.java:556)
	at tk.valoeghese.fc0.client.world.ClientChunk.west(ClientChunk.java:111)
	at tk.valoeghese.fc0.client.render.model.ChunkMesh.buildMesh(ChunkMesh.java:68)
	at tk.valoeghese.fc0.client.world.ClientChunk.rebuildMesh(ClientChunk.java:122)
	at tk.valoeghese.fc0.client.world.ClientChunk.refreshLighting(ClientChunk.java:157)
	at tk.valoeghese.fc0.world.Chunk.lambda$null$0(Chunk.java:197)
	at tk.valoeghese.fc0.client.Client2fc.run(Client2fc.java:137)
	at tk.valoeghese.fc0.client.Main.main(Main.java:8)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at tk.valoeghese.sod.BinaryData.readGzipped(BinaryData.java:115)
	... 24 more

**Comment by valoeghese** [comment]
might hvae been a corrupted save idk
